# Generated by Django 5.0.6 on 2024-05-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.IntegerField(choices=[(0, 'Arcadia'), (1, 'Regina Maria'), (2, 'Synevo'), (100, 'None')], default=100)),
                ('file', models.FileField(upload_to='analize-pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='licenta.analizepdf')),
            ],
        ),
        migrations.CreateModel(
            name='AnalizeRezultate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.CharField(max_length=255)),
                ('is_numeric', models.BooleanField()),
                ('result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('range_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('range_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected', models.BooleanField()),
                ('measurement_unit', models.CharField(max_length=10)),
                ('fromPDF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='licenta.analize')),
            ],
        ),
        migrations.CreateModel(
            name='RadiografiePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.IntegerField(choices=[(0, 'Arcadia'), (1, 'Regina Maria'), (2, 'Synevo'), (100, 'None')], default=100)),
                ('file', models.FileField(upload_to='radiografie-pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
