# Generated by Django 5.0.6 on 2024-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.RenameField(
            model_name='analysisprovider',
            old_name='crops',
            new_name='crops_words',
        ),
        migrations.AddField(
            model_name='analysisprovider',
            name='crops_pixels',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisprovider',
            name='replace_results',
            field=models.JSONField(blank=True),
        ),
    ]
