# Generated by Django 5.0.6 on 2024-05-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0002_analizepdf_analize_analizerezultate_radiografiepdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analizerezultate',
            name='fromPDF',
        ),
        migrations.AddField(
            model_name='analizerezultate',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analizerezultate',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='licenta.analize'),
        ),
    ]
