# Generated by Django 5.0.6 on 2024-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0002_alter_analysis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisprovider',
            name='crops_pixels',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisprovider',
            name='crops_words',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisprovider',
            name='ignored_words',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisprovider',
            name='range_extraction_regex',
            field=models.JSONField(blank=True),
        ),
    ]
