# Generated by Django 5.0.6 on 2024-10-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0003_alter_analysisprovider_crops_pixels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='in_range',
            field=models.BooleanField(null=True),
        ),
    ]
