# Generated by Django 5.0.6 on 2024-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0004_analysisresult_in_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
