# Generated by Django 5.0.6 on 2024-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0004_alter_analizerezultate_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analizerezultate',
            name='range_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='analizerezultate',
            name='range_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
