# Generated by Django 5.0.6 on 2024-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0005_alter_analizerezultate_range_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analize',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
