# Generated by Django 5.0.6 on 2024-11-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0006_analysispdf_doctor_notes_analysispdf_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='doctor_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysiscategoryname',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_names', to='licenta.analysiscategory'),
        ),
    ]
