# Generated by Django 5.0.6 on 2024-11-26 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0007_analysisresult_doctor_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysispdf',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='radiographypdf',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
