# Generated by Django 5.0.6 on 2024-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0008_analysis_modified_analysispdf_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisprovider',
            name='analysis_list',
            field=models.URLField(blank=True),
        ),
    ]
