# Generated by Django 5.0.6 on 2024-11-27 14:49

import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0012_extraanalysiscategories_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisprovider',
            name='analysis_columns',
            field=models.JSONField(default=functools.partial(list, *([0, 1, 2, 3],), **{})),
        ),
    ]
