# Generated by Django 5.0.6 on 2025-01-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0015_user_is_doctor_user_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patients',
        ),
        migrations.CreateModel(
            name='PatientInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255)),
                ('expires', models.DateTimeField()),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_invited', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Invite',
                'verbose_name_plural': 'Patient Invites',
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
