# Generated by Django 5.0.6 on 2025-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0016_remove_user_patients_patientinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinvite',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
