# Generated by Django 5.0.6 on 2025-01-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0017_alter_patientinvite_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinvite',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_invites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
