# Generated by Django 5.0.6 on 2025-01-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0018_alter_patientinvite_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinvite',
            name='token',
        ),
    ]
