# Generated by Django 5.0.6 on 2025-02-01 15:48

import encrypted_model_fields.fields
import licenta.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0021_user_doctor_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='approve_ai_suggestion',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysispdf',
            name='file',
            field=models.FileField(upload_to=licenta.helpers.RandomFileName('analize-pdfs')),
        ),
        migrations.AlterField(
            model_name='radiographypdf',
            name='file',
            field=models.FileField(upload_to=licenta.helpers.RandomFileName('radiografie-pdfs')),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor_proof',
            field=models.FileField(blank=True, null=True, upload_to=licenta.helpers.RandomFileName('doctor-proofs')),
        ),
    ]
