# Generated by Django 5.0.6 on 2025-02-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0022_analysisresult_approve_ai_suggestion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
