# Generated by Django 5.0.6 on 2025-02-03 08:51

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0023_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_new_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=encrypted_model_fields.fields.EncryptedDateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
