# Generated by Django 5.0.6 on 2025-02-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0024_user_accept_new_patients_user_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinvite',
            name='expires',
        ),
    ]
