# Generated by Django 5.0.6 on 2025-02-03 09:30

import licenta.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0025_remove_patientinvite_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=licenta.models.EncryptedDecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=licenta.models.EncryptedDecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
