# Generated by Django 5.1.5 on 2025-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0026_user_height_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_paying',
            field=models.BooleanField(default=False),
        ),
    ]
